### ISSUE TITLE
Unable to rename MainActivity file for Android

### ISSUE THREAD

**Issue by motazalnuweiri** [OutdatedGuy/package_rename#21]
Unable to rename `MainActivity` file for Android, I'm working on Windows 11

Config:
```
package_rename_config:
  android:
    app_name: My App
    package_name: com.test.my_app
    override_old_package: com.example.my_app
    lang: kotlin
```

Error message:
```
PathNotFoundException: Cannot rename file to 'android/app/src/main/kotlin/com/test/my_app/my_app\MainActivity.kt', path = 'android/app/src/main/kotlin/com/example/my_app\MainActivity.kt' (OS Error: The system cannot find the path specified.
, errno = 3)
ERR Code: 255
New MainActivity creation failed!!!
```
