### ISSUE TITLE
build.gradle file not found at: android/app/build.gradle

### ISSUE THREAD

**Issue by jokamax** [OutdatedGuy/package_rename#79]
Hi,

I have a little problem.
I'm on Windows 10 - VSCode

Flutter 3.29.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c236373904 (3 weeks ago) • 2025-03-13 16:17:06 -0400
Engine • revision 18b71d647a
Tools • Dart 3.7.2 • DevTools 2.42.3

And package_rename 1.9.0
I use package rename as is : 
dart run package_rename -p "package_rename_config_868_energia_grupal.yaml"

With file config : 
```
package_rename_config:
  android:
    app_name: Energia Grupal
    package_name: es.energiagrupal.app

  ios:
    app_name: Energia Grupal
    bundle_name: ENERGIAGRUPAL
    package_name: es.energiagrupal.app

  macos:
    app_name: Energia Grupal
    package_name: es.energiagrupal.app
    copyright_notice: Copyright © 2025 Energia Grupal
```

When I launch :
```
Android label set to: `Energia Grupal` (main AndroidManifest.xml)
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
Android package set to: `es.energiagrupal.app` (main AndroidManifest.xml)
Android package set to: `es.energiagrupal.app` (debug AndroidManifest.xml)
Android package set to: `es.energiagrupal.app` (profile AndroidManifest.xml)
build.gradle or build.gradle.kts file not found at: android/app/build.gradle or android/app/build.gradle.kts
```

**build.gradle is not found but : It exist, in the good path.**
VsCode propose to open it from the log...
```
PS C:\Workspace\flutter-projects\betool_mobile_app\android\app> ls


    Répertoire : C:\Workspace\flutter-projects\betool_mobile_app\android\app


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        23/01/2024     10:09                src
-a----        04/04/2025     13:01           2641 build.gradle
```

And the command was launch from : C:\Workspace\flutter-projects\betool_mobile_app\
Can you help me ?

_update : I thought it was because windows, so I tested on a mac : same error_
